apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 919188484580.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 919188484580.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: e4188fd9
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
